-- Fichier qui peuple les tables

-- Pays
insert into pays (nom, code_pays) values ('Etats-Unis', 'USA');
insert into pays (nom, code_pays) values ('Hongrie', 'HON');
insert into pays (nom, code_pays) values ('Jamaïque', 'JAM');
insert into pays (nom, code_pays) values ('Grande-Bretagne', 'GBR');
insert into pays (nom, code_pays) values ('Russie', 'RUS');
insert into pays (nom, code_pays) values ('Japon', 'JAP');
insert into pays (nom, code_pays) values ('Italie', 'ITA');
insert into pays (nom, code_pays) values ('Allemagne', 'ALL');
insert into pays (nom, code_pays) values ('Corée du Sud', 'CDS');
insert into pays (nom, code_pays) values ('Chine', 'CHN');
insert into pays (nom, code_pays) values ('France', 'FRA');
insert into pays (nom, code_pays) values ('Canada', 'CAN');
insert into pays (nom, code_pays) values ('Afrique Du Sud', 'AFS');
insert into pays (nom, code_pays) values ('Grenada', 'GRD');
insert into pays (nom, code_pays) values ('Kenya', 'KEN');
insert into pays (nom, code_pays) values ('Ethiopie', 'ETH');
insert into Pays (nom, code_pays) values('Australie', 'AUS');
insert into Pays (nom, code_pays) values('Pays-Bas', 'HOL');
insert into Pays (nom, code_pays) values('Brésil', 'BRE');
insert into Pays (nom, code_pays) values('Espagne', 'ESP');
insert into Pays (nom, code_pays) values('Croatie', 'CRO');
insert into Pays (nom, code_pays) values('Cuba', 'CUB');
insert into Pays (nom, code_pays) values('Nouvelle-Zélande', 'NZL');
insert into Pays (nom, code_pays) values('Ouzbékistan', 'OZB');
insert into Pays (nom, code_pays) values('Kazakhstan', 'KAZ');
insert into Pays (nom, code_pays) values('Colombie', 'COL');
insert into Pays (nom, code_pays) values('Suisse', 'SUI');
insert into Pays (nom, code_pays) values('Iran', 'IRA');
insert into Pays (nom, code_pays) values('Grèce', 'GRE');
insert into Pays (nom, code_pays) values('Argentine', 'ARG');
insert into Pays (nom, code_pays) values('Danemark', 'DAN');
insert into Pays (nom, code_pays) values('Suède', 'SUE');
insert into Pays (nom, code_pays) values('Ukraine', 'UKR');
insert into Pays (nom, code_pays) values('Serbie', 'SER');
insert into Pays (nom, code_pays) values('Pologne', 'POL');
insert into Pays (nom, code_pays) values('Corée du Nord', 'CDN');
insert into Pays (nom, code_pays) values('Belgique', 'BEL');
insert into Pays (nom, code_pays) values('Thaïlande', 'THA');
insert into Pays (nom, code_pays) values('Slovaquie', 'SLQ');
insert into Pays (nom, code_pays) values('Géorgie', 'GEO');
insert into Pays (nom, code_pays) values('Azerbaïdjan', 'AZE');
insert into Pays (nom, code_pays) values('Biélorussie', 'BIE');
insert into Pays (nom, code_pays) values('Turquie', 'TUR');
insert into Pays (nom, code_pays) values('Arménie', 'ARM');
insert into Pays (nom, code_pays) values('Rép. Tchèque', 'CZE');
insert into Pays (nom, code_pays) values('Slovénie', 'SLO');
insert into Pays (nom, code_pays) values('Indonésie', 'INO');
insert into Pays (nom, code_pays) values('Roumanie', 'ROU');
insert into Pays (nom, code_pays) values('Bahrein', 'BAH');
insert into Pays (nom, code_pays) values('Vietnam', 'VIE');
insert into Pays (nom, code_pays) values('Taiwan', 'TAI');
insert into Pays (nom, code_pays) values('Bahamas', 'BMS');
insert into Pays (nom, code_pays) values('CIO', 'CIO');
insert into Pays (nom, code_pays) values('Côte dIvoire', 'CIV');
insert into Pays (nom, code_pays) values('Fidji', 'FID');
insert into Pays (nom, code_pays) values('Jordanie', 'JOR');
insert into Pays (nom, code_pays) values('Kosovo', 'KOS');
insert into Pays (nom, code_pays) values('Porto-Rico', 'PRC');
insert into Pays (nom, code_pays) values('Singapour', 'SIN');
insert into Pays (nom, code_pays) values('Tadjikistan', 'TAD');
insert into Pays (nom, code_pays) values('Malaisie', 'MAL');
insert into Pays (nom, code_pays) values('Mexique', 'MEX');
insert into Pays (nom, code_pays) values('Algérie', 'ALG');
insert into Pays (nom, code_pays) values('Irlande', 'IRL');
insert into Pays (nom, code_pays) values('Lituanie', 'LIT');
insert into Pays (nom, code_pays) values('Bulgarie', 'BUL');
insert into Pays (nom, code_pays) values('Venezuela', 'VEN');
insert into Pays (nom, code_pays) values('Inde', 'IND');
insert into Pays (nom, code_pays) values('Mongolie', 'MON');
insert into Pays (nom, code_pays) values('Burundi', 'BUR');
insert into Pays (nom, code_pays) values('Niger', 'NIG');
insert into Pays (nom, code_pays) values('Philippines', 'PHI');
insert into Pays (nom, code_pays) values('Qatar', 'QAT');
insert into Pays (nom, code_pays) values('Norvège', 'NOR');
insert into Pays (nom, code_pays) values('Egypte', 'EGY');
insert into Pays (nom, code_pays) values('Tunisie', 'TUN');
insert into Pays (nom, code_pays) values('Israël', 'ISR');
insert into Pays (nom, code_pays) values('Autriche', 'AUT');
insert into Pays (nom, code_pays) values('Emirats Arabes Unis', 'EAU');
insert into Pays (nom, code_pays) values('Estonie', 'EST');
insert into Pays (nom, code_pays) values('Finlande', 'FIN');
insert into Pays (nom, code_pays) values('Maroc', 'MAR');
insert into Pays (nom, code_pays) values('Moldavie', 'MOL');
insert into Pays (nom, code_pays) values('Nigeria', 'NGA');
insert into Pays (nom, code_pays) values('Portugal', 'POR');
insert into Pays (nom, code_pays) values('Rép. Dominicaine', 'DOM');
insert into Pays (nom, code_pays) values('Trinité-et-Tobago', 'TRI');

-- Athlete
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Michael Phelps','USA',5,1,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Kathleen Ledecky','USA',4,1,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Simone Biles','USA',4,0,1, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Katinka Hosszu','HON',3,1,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Ryan Murphy','USA',3,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Danuta Kozak','HON',3,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Usain Bolt','JAM',3,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Jason Kenny','GBR',3,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Simone Manuel','USA',2,2,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Madeline (Maya) Dirado','USA',2,1,1, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Elaine Thompson','JAM',2,1,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Allyson Felix','USA',2,1,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Nathan Adrian','USA',2,0,2, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Max Whitlock','GBR',2,0,1, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Anthony Ervin','USA',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Lilly King','USA',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Yana Egorian','RUS',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Kohei Uchimura','JAP',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Niccolo Campriani','ITA',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Sebastian Brendel','ALL',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Gabriella Szabo','HON',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Marcus Gross','ALL',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Max Rendschmidt','ALL',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Hye-jin Chang','CDS',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Bon-chan Ku','CDS',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Long Ma','CHN',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Ning Ding','CHN',2,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Justin Gatlin','USA',0,1,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Andre De Grasse','CAN',0,1,2, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Christophe Lemaitre','FRA',0,0,1, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Wayde Von Niekerk','AFS',1,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Kirani James','GRD',0,1,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('LaShawn Merritt','USA',1,0,1, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Eliud Kipchoge','KEN',1,0,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Feyisa Lilesa','ETH',0,1,0, 1);
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport) values('Galen Rupp','USA',0,0,1, 1);

-- EpreuveIndividuelle
insert into epreuveindividuelle (nom_epreuve, id_sport) values('100m', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('400m', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('marathon', 1);

-- Athlete_EpreuveIndividuelle
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(7,1,'or','9mn81"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(28,1,'argent','9mn89"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(29,1,'bronze','9mn91"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(7,2,'or','19mn78"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(29,2,'argent','20mn02"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(30,2,'bronze','20mn12"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(31,3,'or','43mn03"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(32,3,'argent','43mn76"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(33,3,'bronze','43mn85"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(34,4,'or','2h08mn44"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(35,4,'argent','2h09mn54"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(36,4,'bronze','2h10mn05"');
