-- Fichier qui peuple les tables

-- Pays
insert into pays (nom, code_pays) values ('Etats-Unis', 'USA');
insert into pays (nom, code_pays) values ('Hongrie', 'HON');
insert into pays (nom, code_pays) values ('Jamaïque', 'JAM');
insert into pays (nom, code_pays) values ('Grande-Bretagne', 'GBR');
insert into pays (nom, code_pays) values ('Russie', 'RUS');
insert into pays (nom, code_pays) values ('Japon', 'JAP');
insert into pays (nom, code_pays) values ('Italie', 'ITA');
insert into pays (nom, code_pays) values ('Allemagne', 'ALL');
insert into pays (nom, code_pays) values ('Corée du Sud', 'CDS');
insert into pays (nom, code_pays) values ('Chine', 'CHN');
insert into pays (nom, code_pays) values ('France', 'FRA');
insert into pays (nom, code_pays) values ('Canada', 'CAN');
insert into pays (nom, code_pays) values ('Afrique Du Sud', 'AFS');
insert into pays (nom, code_pays) values ('Grenada', 'GRD');
insert into pays (nom, code_pays) values ('Kenya', 'KEN');
insert into pays (nom, code_pays) values ('Ethiopie', 'ETH');
insert into Pays (nom, code_pays) values('Australie', 'AUS');
insert into Pays (nom, code_pays) values('Pays-Bas', 'HOL');
insert into Pays (nom, code_pays) values('Brésil', 'BRE');
insert into Pays (nom, code_pays) values('Espagne', 'ESP');
insert into Pays (nom, code_pays) values('Croatie', 'CRO');
insert into Pays (nom, code_pays) values('Cuba', 'CUB');
insert into Pays (nom, code_pays) values('Nouvelle-Zélande', 'NZL');
insert into Pays (nom, code_pays) values('Ouzbékistan', 'OZB');
insert into Pays (nom, code_pays) values('Kazakhstan', 'KAZ');
insert into Pays (nom, code_pays) values('Colombie', 'COL');
insert into Pays (nom, code_pays) values('Suisse', 'SUI');
insert into Pays (nom, code_pays) values('Iran', 'IRA');
insert into Pays (nom, code_pays) values('Grèce', 'GRE');
insert into Pays (nom, code_pays) values('Argentine', 'ARG');
insert into Pays (nom, code_pays) values('Danemark', 'DAN');
insert into Pays (nom, code_pays) values('Suède', 'SUE');
insert into Pays (nom, code_pays) values('Ukraine', 'UKR');
insert into Pays (nom, code_pays) values('Serbie', 'SER');
insert into Pays (nom, code_pays) values('Pologne', 'POL');
insert into Pays (nom, code_pays) values('Corée du Nord', 'CDN');
insert into Pays (nom, code_pays) values('Belgique', 'BEL');
insert into Pays (nom, code_pays) values('Thaïlande', 'THA');
insert into Pays (nom, code_pays) values('Slovaquie', 'SLQ');
insert into Pays (nom, code_pays) values('Géorgie', 'GEO');
insert into Pays (nom, code_pays) values('Azerbaïdjan', 'AZE');
insert into Pays (nom, code_pays) values('Biélorussie', 'BIE');
insert into Pays (nom, code_pays) values('Turquie', 'TUR');
insert into Pays (nom, code_pays) values('Arménie', 'ARM');
insert into Pays (nom, code_pays) values('Rép. Tchèque', 'CZE');
insert into Pays (nom, code_pays) values('Slovénie', 'SLO');
insert into Pays (nom, code_pays) values('Indonésie', 'INO');
insert into Pays (nom, code_pays) values('Roumanie', 'ROU');
insert into Pays (nom, code_pays) values('Bahrein', 'BAH');
insert into Pays (nom, code_pays) values('Vietnam', 'VIE');
insert into Pays (nom, code_pays) values('Taiwan', 'TAI');
insert into Pays (nom, code_pays) values('Bahamas', 'BMS');
insert into Pays (nom, code_pays) values('CIO', 'CIO');
insert into Pays (nom, code_pays) values('Côte dIvoire', 'CIV');
insert into Pays (nom, code_pays) values('Fidji', 'FID');
insert into Pays (nom, code_pays) values('Jordanie', 'JOR');
insert into Pays (nom, code_pays) values('Kosovo', 'KOS');
insert into Pays (nom, code_pays) values('Porto-Rico', 'PRC');
insert into Pays (nom, code_pays) values('Singapour', 'SIN');
insert into Pays (nom, code_pays) values('Tadjikistan', 'TAD');
insert into Pays (nom, code_pays) values('Malaisie', 'MAL');
insert into Pays (nom, code_pays) values('Mexique', 'MEX');
insert into Pays (nom, code_pays) values('Algérie', 'ALG');
insert into Pays (nom, code_pays) values('Irlande', 'IRL');
insert into Pays (nom, code_pays) values('Lituanie', 'LIT');
insert into Pays (nom, code_pays) values('Bulgarie', 'BUL');
insert into Pays (nom, code_pays) values('Venezuela', 'VEN');
insert into Pays (nom, code_pays) values('Inde', 'IND');
insert into Pays (nom, code_pays) values('Mongolie', 'MON');
insert into Pays (nom, code_pays) values('Burundi', 'BUR');
insert into Pays (nom, code_pays) values('Niger', 'NIG');
insert into Pays (nom, code_pays) values('Philippines', 'PHI');
insert into Pays (nom, code_pays) values('Qatar', 'QAT');
insert into Pays (nom, code_pays) values('Norvège', 'NOR');
insert into Pays (nom, code_pays) values('Egypte', 'EGY');
insert into Pays (nom, code_pays) values('Tunisie', 'TUN');
insert into Pays (nom, code_pays) values('Israël', 'ISR');
insert into Pays (nom, code_pays) values('Autriche', 'AUT');
insert into Pays (nom, code_pays) values('Emirats Arabes Unis', 'EAU');
insert into Pays (nom, code_pays) values('Estonie', 'EST');
insert into Pays (nom, code_pays) values('Finlande', 'FIN');
insert into Pays (nom, code_pays) values('Maroc', 'MAR');
insert into Pays (nom, code_pays) values('Moldavie', 'MOL');
insert into Pays (nom, code_pays) values('Nigeria', 'NGA');
insert into Pays (nom, code_pays) values('Portugal', 'POR');
insert into Pays (nom, code_pays) values('Rép. Dominicaine', 'DOM');
insert into Pays (nom, code_pays) values('Trinité-et-Tobago', 'TRI');

-- Athlete
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Justin Gatlin','USA',0,1,0, 1, TO_DATE('10/02/1982', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Andre De Grasse','CAN',0,1,2, 1, TO_DATE('10/11/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Usain Bolt','JAM',3,0,0, 1, TO_DATE('21/08/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Christophe Lemaitre','FRA',0,0,1, 1, TO_DATE('11/06/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Wayde Van Niekerk','AFS',1,0,0, 1, TO_DATE('15/07/1992', 'DD/MM//YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Kirani James','GRD',0,1,0, 1, TO_DATE('1/09/1992','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('LaShawn Merritt','USA',1,0,1, 1, TO_DATE('27/06/1986','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Elaine Thompson','JAM',2,1,0, 2, TO_DATE('28/06/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Tori Bowie','USA',1,1,1, 2, TO_DATE('27/08/1990','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Shelly-Ann Fraser-Pryce',' JAM',0,1,1, 2, TO_DATE('27/12/1986','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Dafne Schippers',' HOL',0,1,0, 2, TO_DATE('15/06/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Shaunae Miller',' BAH',1,0,0, 2, TO_DATE('15/04/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Allyson Felix','USA',2,1,0, 2, TO_DATE('18/11/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Shericka Jackson',' JAM',0,1,1, 2, TO_DATE('16/07/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Eliud Kipchoge','KEN',1,0,0, 1, TO_DATE('05/11/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Feyisa Lilesa','ETH',0,1,0, 1, TO_DATE('01/02/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Galen Rupp','USA',0,0,1, 1, TO_DATE('08/05/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Jemima Sumgong',' KEN',1,0,0, 2, TO_DATE('21/12/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Eunice Jepkirui Kirwa',' BRN',0,1,0, 2, TO_DATE('20/05/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Mare Dibaba',' ETH',0,0,1, 2, TO_DATE('20/10/1989', 'DD/MM/YYYY'));

--Pour calculer le total de nb_medailles
update athlete set nb_medailles_total=(select (a.nb_medailles_or+a.nb_medailles_argent+a.nb_medailles_bronze) from athlete a where a.id_athlete = athlete.id_athlete);

-- EpreuveIndividuelle
insert into epreuveindividuelle (nom_epreuve, id_sport) values('100m (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('100m (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('400m (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('400m (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('marathon (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('marathon (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('lancer de poids (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('lancer de poids (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('lancer de marteau (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('lancer de marteau (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('lancer de javelot (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('lancer de javelot (F)', 2);

-- Athlete_EpreuveIndividuelle
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(7,1,'or','9mn81"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(28,1,'argent','9mn89"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(29,1,'bronze','9mn91"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(7,2,'or','19mn78"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(29,2,'argent','20mn02"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(30,2,'bronze','20mn12"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(31,3,'or','43mn03"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(32,3,'argent','43mn76"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(33,3,'bronze','43mn85"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(34,4,'or','2h08mn44"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(35,4,'argent','2h09mn54"');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, prix, performance) values(36,4,'bronze','2h10mn05"');

-- Sport
insert into sport (nom_sport, categorie) values ('Athletisme', 'Hommes');
insert into sport (nom_sport, categorie) values ('Athletisme', 'Femmes');
insert into sport (nom_sport, categorie) values ('Aviron', 'Hommes');
insert into sport (nom_sport, categorie) values ('Aviron', 'Femmes');
insert into sport (nom_sport, categorie) values ('BMX', 'Hommes');
insert into sport (nom_sport, categorie) values ('BMX', 'Femmes');
insert into sport (nom_sport, categorie) values ('Badminton', 'Hommes');
insert into sport (nom_sport, categorie) values ('Badminton', 'Femmes');
insert into sport (nom_sport, categorie) values ('Basket', 'Hommes');
insert into sport (nom_sport, categorie) values ('Basket', 'Femmes');
insert into sport (nom_sport, categorie) values ('Beach-Volley', 'Hommes');
insert into sport (nom_sport, categorie) values ('Beach-Volley', 'Femmes');
insert into sport (nom_sport, categorie) values ('Boxe', 'Hommes');
insert into sport (nom_sport, categorie) values ('Boxe', 'Femmes');
insert into sport (nom_sport, categorie) values ('Canoë-kayak', 'Hommes');
insert into sport (nom_sport, categorie) values ('Canoë-kayak', 'Femmes');
insert into sport (nom_sport, categorie) values ('Cyclisme sur piste', 'Hommes');
insert into sport (nom_sport, categorie) values ('Cyclisme sur piste', 'Femmes');
insert into sport (nom_sport, categorie) values ('Cyclisme sur route', 'Hommes');
insert into sport (nom_sport, categorie) values ('Cyclisme sur route', 'Femmes');
insert into sport (nom_sport, categorie) values ('Equitation', 'Hommes');
insert into sport (nom_sport, categorie) values ('Equitation', 'Femmes');
insert into sport (nom_sport, categorie) values ('Escrime', 'Hommes');
insert into sport (nom_sport, categorie) values ('Escrime', 'Femmes');
insert into sport (nom_sport, categorie) values ('Football', 'Hommes');
insert into sport (nom_sport, categorie) values ('Football', 'Femmes');
insert into sport (nom_sport, categorie) values ('Golf', 'Hommes');
insert into sport (nom_sport, categorie) values ('Golf', 'Femmes');
insert into sport (nom_sport, categorie) values ('Gymnastique', 'Hommes');
insert into sport (nom_sport, categorie) values ('Gymnastique', 'Femmes');
insert into sport (nom_sport, categorie) values ('Gymnastique rythmique', 'Hommes');
insert into sport (nom_sport, categorie) values ('Gymnastique rytmique', 'Femmes');
insert into sport (nom_sport, categorie) values ('Haltérophilie', 'Hommes');
insert into sport (nom_sport, categorie) values ('Haltérophilie', 'Femmes');
insert into sport (nom_sport, categorie) values ('Handball', 'Hommes');
insert into sport (nom_sport, categorie) values ('Handball', 'Femmes');
insert into sport (nom_sport, categorie) values ('Hockey sur gazon', 'Hommes');
insert into sport (nom_sport, categorie) values ('Hockey sur gazon', 'Femmes');
insert into sport (nom_sport, categorie) values ('Judo', 'Hommes');
insert into sport (nom_sport, categorie) values ('Judo', 'Femmes');
insert into sport (nom_sport, categorie) values ('Lutte Gréco-romaine', 'Hommes');
insert into sport (nom_sport, categorie) values ('Lutte Gréco-romaine', 'Femmes');
insert into sport (nom_sport, categorie) values ('Lutte libre', 'Hommes');
insert into sport (nom_sport, categorie) values ('Lutte libre', 'Femmes');
insert into sport (nom_sport, categorie) values ('Natation', 'Hommes');
insert into sport (nom_sport, categorie) values ('Natation', 'Femmes');
insert into sport (nom_sport, categorie) values ('Natation en eau libre', 'Hommes');
insert into sport (nom_sport, categorie) values ('Natation en eau libre', 'Femmes');
insert into sport (nom_sport, categorie) values ('Natation synchoronise', 'Hommes');
insert into sport (nom_sport, categorie) values ('Natation synchonorise', 'Femmes');
insert into sport (nom_sport, categorie) values ('Pentathlon moderne', 'Hommes');
insert into sport (nom_sport, categorie) values ('Pentathlon moderne', 'Femmes');
insert into sport (nom_sport, categorie) values ('Plongeon', 'Hommes');
insert into sport (nom_sport, categorie) values ('Plongeon', 'Femmes');
insert into sport (nom_sport, categorie) values ('Rugby á VII', 'Hommes');
insert into sport (nom_sport, categorie) values ('Rugby á VII', 'Femmes');
insert into sport (nom_sport, categorie) values ('Taekwondo', 'Hommes');
insert into sport (nom_sport, categorie) values ('Taekwondo', 'Femmes');
insert into sport (nom_sport, categorie) values ('Tennis', 'Hommes');
insert into sport (nom_sport, categorie) values ('Tennis', 'Femmes');
insert into sport (nom_sport, categorie) values ('Tennis de table', 'Hommes');
insert into sport (nom_sport, categorie) values ('Tennis de table', 'Femmes');
insert into sport (nom_sport, categorie) values ('Tir', 'Hommes');
insert into sport (nom_sport, categorie) values ('Tir', 'Femmes');
insert into sport (nom_sport, categorie) values ('Tir á larc', 'Hommes');
insert into sport (nom_sport, categorie) values ('Tir á larc', 'Femmes');
insert into sport (nom_sport, categorie) values ('Trampoline', 'Hommes');
insert into sport (nom_sport, categorie) values ('Trampoline', 'Femmes');
insert into sport (nom_sport, categorie) values ('Triathlon', 'Hommes');
insert into sport (nom_sport, categorie) values ('Triathlon', 'Femmes');
insert into sport (nom_sport, categorie) values ('VTT', 'Hommes');
insert into sport (nom_sport, categorie) values ('VTT', 'Femmes');
insert into sport (nom_sport, categorie) values ('Voile', 'Hommes');
insert into sport (nom_sport, categorie) values ('Voile', 'Femmes');
insert into sport (nom_sport, categorie) values ('Volley-ball', 'Hommes');
insert into sport (nom_sport, categorie) values ('Volley-ball', 'Femmes');
insert into sport (nom_sport, categorie) values ('Water polo', 'Hommes');
insert into sport (nom_sport, categorie) values ('Water polo', 'Femmes');

--Equipes
insert into equipe(code_pays, id_sport) values('DAN', 35); --pour handball hommes
insert into equipe(code_pays, id_sport) values('FRA', 35);
insert into equipe(code_pays, id_sport) values('ALL', 35);
insert into equipe(code_pays, id_sport) values('RUS', 36); --pour handball femmes
insert into equipe(code_pays, id_sport) values('FRA', 36);
insert into equipe(code_pays, id_sport) values('NOR', 36);

--EpreuveCollective
insert into epreuvecollective (id_sport) values (35);
insert into epreuvecollective (id_sport) values (36);

--Equipe_EpreuveCollective
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(1, 1, 'or');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(1, 2, 'argent');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(1, 3, 'bronze');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(2, 4, 'or');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(2, 5, 'argent');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(2, 6, 'bronze');
