-- Fichier qui peuple les tables

-- Pays
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Etats-Unis', 'USA',46,37,38);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Grande-Bretagne', 'GBR',27,23,17);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Chine', 'CHN',26,18,26);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Russie', 'RUS',19,18,19);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Allemagne', 'ALL',17,10,15);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Japon', 'JAP',12,8,21);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('France', 'FRA',10,18,14);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Corée du Sud', 'CDS',9,3,9);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Italie', 'ITA',8,12,8);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Australie', 'AUS',8,11,10);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Pays-Bas', 'HOL',8,7,4);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Hongrie', 'HON',8,3,4);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Brésil', 'BRE',7,6,6);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Espagne', 'ESP',7,4,6);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Kenya', 'KEN',6,6,1);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Jamaïque', 'JAM',6,3,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Croatie', 'CRO',5,3,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Cuba', 'CUB',5,2,4);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Nouvelle-Zélande', 'NZL',4,9,5);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Canada', 'CAN',4,3,15);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Ouzbékistan', 'OZB',4,2,7);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Kazakhstan', 'KAZ',3,5,9);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Colombie', 'COL',3,2,3);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Suisse', 'SUI',3,2,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Iran', 'IRA',3,1,4);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Grèce', 'GRE',3,1,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Argentine', 'ARG',3,1,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Danemark', 'DAN',2,6,7);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Suède', 'SUE',2,6,3);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Afrique Du Sud', 'AFS',2,6,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Ukraine', 'UKR',2,5,4);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Serbie', 'SER',2,4,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Pologne', 'POL',2,3,6);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Corée du Nord', 'CDN',2,3,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Belgique', 'BEL',2,2,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Thaïlande', 'THA',2,2,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Slovaquie', 'SLQ',2,2,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Géorgie', 'GEO',2,1,4);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Azerbaïdjan', 'AZE',1,7,10);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Biélorussie', 'BIE',1,4,4);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Turquie', 'TUR',1,3,4);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Arménie', 'ARM',1,3,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Rép. Tchèque', 'CZE',1,2,7);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Ethiopie', 'ETH',1,2,5);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Slovénie', 'SLO',1,2,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Indonésie', 'INO',1,2,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Roumanie', 'ROU',1,1,3);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Bahrein', 'BRN',1,1,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Vietnam', 'VIE',1,1,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Taiwan', 'TAI',1,0,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Bahamas', 'BAH',1,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('CIO', 'CIO',1,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Côte dIvoire', 'CIV',1,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Fidji', 'FID',1,0,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Jordanie', 'JOR',1,0,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Kosovo', 'KOS',1,0,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Porto-Rico', 'PRC',1,0,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Singapour', 'SIN',1,0,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Tadjikistan', 'TAD',1,0,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Malaisie', 'MAL',0,4,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Mexique', 'MEX',0,3,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Algérie', 'ALG',0,2,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Irlande', 'IRL',0,2,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Lituanie', 'LIT',0,1,3);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Bulgarie', 'BUL',0,1,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Venezuela', 'VEN',0,1,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Inde', 'IND',0,1,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Mongolie', 'MON',0,1,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Burundi', 'BUR',0,1,0);
insert into pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values ('Grenada', 'GRD',0,1,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Niger', 'NIG',0,1,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Philippines', 'PHI',0,1,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Qatar', 'QAT',0,1,0);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Norvège', 'NOR',0,0,4);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Egypte', 'EGY',0,0,3);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Tunisie', 'TUN',0,0,3);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Israël', 'ISR',0,0,2);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Autriche', 'AUT',0,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Emirats Arabes Unis', 'EAU',0,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Estonie', 'EST',0,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Finlande', 'FIN',0,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Maroc', 'MAR',0,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Moldavie', 'MOL',0,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Nigeria', 'NGA',0,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Portugal', 'POR',0,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Rép. Dominicaine', 'DOM',0,0,1);
insert into Pays (nom, code_pays, nb_medailles_or, nb_medailles_argent, nb_medailles_bronze) values('Trinité-et-Tobago', 'TRI',0,0,1);

--Pour le nombre total de medailles
update pays set nb_medailles_total=(select (p.nb_medailles_or+p.nb_medailles_argent+p.nb_medailles_bronze) from pays p where p.id_pays = pays.id_pays);
--Pour la colonne rang, pour faire une rangement
create view rank as select p1.*, rank() over(order by p1.nb_medailles_or desc, p1.nb_medailles_argent desc, p1.nb_medailles_bronze desc) from pays p1, pays p2 where p1.code_pays=p2.code_pays;
update pays set rang=(select rank from rank where rank.id_pays=pays.id_pays);


-- Sport
insert into sport (nom_sport, categorie) values ('Athletisme', 'Hommes');
insert into sport (nom_sport, categorie) values ('Athletisme', 'Femmes');
insert into sport (nom_sport, categorie) values ('Aviron', 'Hommes');
insert into sport (nom_sport, categorie) values ('Aviron', 'Femmes');
insert into sport (nom_sport, categorie) values ('BMX', 'Hommes');
insert into sport (nom_sport, categorie) values ('BMX', 'Femmes');
insert into sport (nom_sport, categorie) values ('Badminton', 'Hommes');
insert into sport (nom_sport, categorie) values ('Badminton', 'Femmes');
insert into sport (nom_sport, categorie) values ('Basket', 'Hommes');
insert into sport (nom_sport, categorie) values ('Basket', 'Femmes');
insert into sport (nom_sport, categorie) values ('Beach-Volley', 'Hommes');
insert into sport (nom_sport, categorie) values ('Beach-Volley', 'Femmes');
insert into sport (nom_sport, categorie) values ('Boxe', 'Hommes');
insert into sport (nom_sport, categorie) values ('Boxe', 'Femmes');
insert into sport (nom_sport, categorie) values ('Canoë-kayak', 'Hommes');
insert into sport (nom_sport, categorie) values ('Canoë-kayak', 'Femmes');
insert into sport (nom_sport, categorie) values ('Cyclisme sur piste', 'Hommes');
insert into sport (nom_sport, categorie) values ('Cyclisme sur piste', 'Femmes');
insert into sport (nom_sport, categorie) values ('Cyclisme sur route', 'Hommes');
insert into sport (nom_sport, categorie) values ('Cyclisme sur route', 'Femmes');
insert into sport (nom_sport, categorie) values ('Equitation', 'Hommes');
insert into sport (nom_sport, categorie) values ('Equitation', 'Femmes');
insert into sport (nom_sport, categorie) values ('Escrime', 'Hommes');
insert into sport (nom_sport, categorie) values ('Escrime', 'Femmes');
insert into sport (nom_sport, categorie) values ('Football', 'Hommes');
insert into sport (nom_sport, categorie) values ('Football', 'Femmes');
insert into sport (nom_sport, categorie) values ('Golf', 'Hommes');
insert into sport (nom_sport, categorie) values ('Golf', 'Femmes');
insert into sport (nom_sport, categorie) values ('Gymnastique', 'Hommes');
insert into sport (nom_sport, categorie) values ('Gymnastique', 'Femmes');
insert into sport (nom_sport, categorie) values ('Gymnastique rythmique', 'Hommes');
insert into sport (nom_sport, categorie) values ('Gymnastique rytmique', 'Femmes');
insert into sport (nom_sport, categorie) values ('Haltérophilie', 'Hommes');
insert into sport (nom_sport, categorie) values ('Haltérophilie', 'Femmes');
insert into sport (nom_sport, categorie) values ('Handball', 'Hommes');
insert into sport (nom_sport, categorie) values ('Handball', 'Femmes');
insert into sport (nom_sport, categorie) values ('Hockey sur gazon', 'Hommes');
insert into sport (nom_sport, categorie) values ('Hockey sur gazon', 'Femmes');
insert into sport (nom_sport, categorie) values ('Judo', 'Hommes');
insert into sport (nom_sport, categorie) values ('Judo', 'Femmes');
insert into sport (nom_sport, categorie) values ('Lutte Gréco-romaine', 'Hommes');
insert into sport (nom_sport, categorie) values ('Lutte Gréco-romaine', 'Femmes');
insert into sport (nom_sport, categorie) values ('Lutte libre', 'Hommes');
insert into sport (nom_sport, categorie) values ('Lutte libre', 'Femmes');
insert into sport (nom_sport, categorie) values ('Natation', 'Hommes');
insert into sport (nom_sport, categorie) values ('Natation', 'Femmes');
insert into sport (nom_sport, categorie) values ('Natation en eau libre', 'Hommes');
insert into sport (nom_sport, categorie) values ('Natation en eau libre', 'Femmes');
insert into sport (nom_sport, categorie) values ('Natation synchoronise', 'Hommes');
insert into sport (nom_sport, categorie) values ('Natation synchonorise', 'Femmes');
insert into sport (nom_sport, categorie) values ('Pentathlon moderne', 'Hommes');
insert into sport (nom_sport, categorie) values ('Pentathlon moderne', 'Femmes');
insert into sport (nom_sport, categorie) values ('Plongeon', 'Hommes');
insert into sport (nom_sport, categorie) values ('Plongeon', 'Femmes');
insert into sport (nom_sport, categorie) values ('Rugby á VII', 'Hommes');
insert into sport (nom_sport, categorie) values ('Rugby á VII', 'Femmes');
insert into sport (nom_sport, categorie) values ('Taekwondo', 'Hommes');
insert into sport (nom_sport, categorie) values ('Taekwondo', 'Femmes');
insert into sport (nom_sport, categorie) values ('Tennis', 'Hommes');
insert into sport (nom_sport, categorie) values ('Tennis', 'Femmes');
insert into sport (nom_sport, categorie) values ('Tennis de table', 'Hommes');
insert into sport (nom_sport, categorie) values ('Tennis de table', 'Femmes');
insert into sport (nom_sport, categorie) values ('Tir', 'Hommes');
insert into sport (nom_sport, categorie) values ('Tir', 'Femmes');
insert into sport (nom_sport, categorie) values ('Tir á larc', 'Hommes');
insert into sport (nom_sport, categorie) values ('Tir á larc', 'Femmes');
insert into sport (nom_sport, categorie) values ('Trampoline', 'Hommes');
insert into sport (nom_sport, categorie) values ('Trampoline', 'Femmes');
insert into sport (nom_sport, categorie) values ('Triathlon', 'Hommes');
insert into sport (nom_sport, categorie) values ('Triathlon', 'Femmes');
insert into sport (nom_sport, categorie) values ('VTT', 'Hommes');
insert into sport (nom_sport, categorie) values ('VTT', 'Femmes');
insert into sport (nom_sport, categorie) values ('Voile', 'Hommes');
insert into sport (nom_sport, categorie) values ('Voile', 'Femmes');
insert into sport (nom_sport, categorie) values ('Volley-ball', 'Hommes');
insert into sport (nom_sport, categorie) values ('Volley-ball', 'Femmes');
insert into sport (nom_sport, categorie) values ('Water polo', 'Hommes');
insert into sport (nom_sport, categorie) values ('Water polo', 'Femmes');

-- Athlete
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Justin Gatlin','USA',0,1,0, 1, TO_DATE('10/02/1982', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Andre De Grasse','CAN',0,1,2, 1, TO_DATE('10/11/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Usain Bolt','JAM',3,0,0, 1, TO_DATE('21/08/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Christophe Lemaitre','FRA',0,0,1, 1, TO_DATE('11/06/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Wayde Van Niekerk','AFS',1,0,0, 1, TO_DATE('15/07/1992', 'DD/MM//YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Kirani James','GRD',0,1,0, 1, TO_DATE('1/09/1992','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('LaShawn Merritt','USA',1,0,1, 1, TO_DATE('27/06/1986','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Elaine Thompson','JAM',2,1,0, 2, TO_DATE('28/06/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Tori Bowie','USA',1,1,1, 2, TO_DATE('27/08/1990','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Shelly-Ann Fraser-Pryce',' JAM',0,1,1, 2, TO_DATE('27/12/1986','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Dafne Schippers','HOL',0,1,0, 2, TO_DATE('15/06/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Shaunae Miller','BAH',1,0,0, 2, TO_DATE('15/04/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Allyson Felix','USA',2,1,0, 2, TO_DATE('18/11/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Shericka Jackson','JAM',0,1,1, 2, TO_DATE('16/07/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Eliud Kipchoge','KEN',1,0,0, 1, TO_DATE('05/11/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Feyisa Lilesa','ETH',0,1,0, 1, TO_DATE('01/02/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Galen Rupp','USA',0,0,1, 1, TO_DATE('08/05/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Jemima Sumgong','KEN',1,0,0, 2, TO_DATE('21/12/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Eunice Jepkirui Kirwa','BRN',0,1,0, 2, TO_DATE('20/05/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Mare Dibaba','ETH',0,0,1, 2, TO_DATE('20/10/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Joseph Schooling','SIN',1,0,0, 45, TO_DATE('16/05/1995','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Michael Phelps','USA',5,1,0, 45, TO_DATE('30/06/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Lazslo Cseh','HON',0,1,0, 45, TO_DATE('03/12/1985','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Chad Le Clos','AFS',0,2,0, 45, TO_DATE('12/04/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Masato Sakai','JAP',0,1,0, 45, TO_DATE('14/10/1983', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Tamas Kenderesi','HON',0,0,1, 45, TO_DATE('13/12/1996', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Kosuke Hagino','JAP',1,1,1, 45, TO_DATE('15/08/1994','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Shun Wang','CHN',0,0,1, 45, TO_DATE('11/02/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Sarah Sjoestrom','SUE',1,1,1, 46, TO_DATE('17/03/1993','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Penny Oleksiak','CAN',1,1,2, 46, TO_DATE('13/06/2000', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Dana Vollmer','USA',1,1,1, 46, TO_DATE('13/11/1987', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Mireia Belmonte Garcia','ESP',1,0,1, 46, TO_DATE('10/10/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Madeline Groves','AUS',0,1,0, 46, TO_DATE('25/05/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Natsumi Hoshi','JAP',0,0,1, 46, TO_DATE('28/08/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Katinka Hosszu','HON',3,1,0, 46, TO_DATE('03/05/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Siobhan-Marie Oconnor','GBR',0,1,0, 46, TO_DATE('29/11/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Madeline (Maya) Dirado','USA',2,1,1, 46, TO_DATE('05/04/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Caeleb Dressel','USA',1,0,0, 45, TO_DATE('16/08/1996','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Ryan Held','USA',1,0,0, 45, TO_DATE('27/06/1995','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Nathan Adrian','USA',2,0,2, 45, TO_DATE('07/12/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('James (Jimmy) Feigen','USA',1,0,0, 45, TO_DATE('26/09/1989','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Blake Pieroni','USA',1,0,0, 45,TO_DATE('15/11/1995','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Anthony Ervin','USA',2,0,0, 45, TO_DATE('26/05/1981', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Mehdy Metella','FRA',0,1,0, 45, TO_DATE('17/07/1982','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Fabien Gilot','FRA',0,1,0, 45, TO_DATE('27/04/1984','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Florent Manaudou','FRA',0,2,0, 45, TO_DATE('12/11/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Jérémy Stravius','FRA',0,1,0, 45, TO_DATE('14/07/1988','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Clément Mignon','FRA',0,1,0, 45, TO_DATE('21/01/1993','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('William Meynard','FRA',0,1,0, 45, TO_DATE('11/07/1987','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('James Roberts','AUS',0,0,1, 45, TO_DATE('11/04/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Kyle Chalmers','AUS',1,0,2, 45, TO_DATE('25/06/1998', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('James Magnussen','AUS',0,0,1, 45, TO_DATE('11/04/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Cameron Mcevoy','AUS',0,0,1, 45, TO_DATE('13/05/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Matthew Abood','AUS',0,0,1, 45, TO_DATE('28/06/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Emma Mckeon','AUS',1,2,1, 46, TO_DATE('24/05/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Britanny Elmslie','AUS',1,0,0, 46, TO_DATE('19/06/1994','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Bronte Campbell','AUS',1,0,0, 46, TO_DATE('14/05/1994','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Cate Campbell','AUS',1,1,0, 46, TO_DATE('20/05/1992','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Madison Wilson','AUS',1,0,0, 46, TO_DATE('31/05/1994','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Simone Manuel','USA',2,2,0, 46, TO_DATE('02/08/1996', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Abbigail Weitzeil','USA',0,1,0, 46, TO_DATE('03/12/1996', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Kathleen Ledecky','USA',4,1,0, 46, TO_DATE('17/03/1997', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Amanda Weir','USA',0,1,0, 46, TO_DATE('11/03/1986','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Lia Neal','USA',0,1,0, 46, TO_DATE('13/02/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Allison Schmitt','USA',1,1,0, 46, TO_DATE('07/06/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Sandrine Mainville','CAN',0,0,1, 46, TO_DATE('20/03/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Chantal Van Landeghem','CAN',0,0,1, 46, TO_DATE('05/03/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Taylor Ruck','CAN',0,0,2, 46, TO_DATE('28/05/2000', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Michelle Williams','CAN',0,0,1, 46, TO_DATE('02/01/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Conor Dwyer','USA',1,0,1, 45, TO_DATE('10/01/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Francis Haas','USA',1,0,0, 45, TO_DATE('13/12/1996','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Ryan Lochte','USA',1,0,0, 45, TO_DATE('03/08/1984','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Clark Smith','USA',1,0,0, 45, TO_DATE('17/04/1995','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Jack Conger','USA',1,0,0, 45,TO_DATE('26/09/1994','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Gunnar Bentz','USA',1,0,0, 45, TO_DATE('03/01/1996','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Stephen Milne','GBR',0,1,0, 45, TO_DATE('29/04/1994', 'DD/MM/YYYY '));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Duncan Scott','GBR',0,2,0, 45, TO_DATE('06/05/1997', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Daniel Wallace','GBR',0,1,0, 45, TO_DATE('14/04/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('James Guy','GBR',0,2,0, 45, TO_DATE('26/11/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Robert Renwick','GBR',0,1,0, 45, TO_DATE('21/07/1988','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Naito Ehara','JAP',0,0,1, 45, TO_DATE('30/07/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Yuki Kobori','JAP',0,0,1, 45, TO_DATE('25/11/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Takeshi Matsuda','JAP',0,0,1, 45, TO_DATE('23/06/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Leah Smith','USA',1,0,1, 46, TO_DATE('19/04/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Missy Franklin','USA',1,0,0, 46, TO_DATE('10/05/1995','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Melanie Margalis','USA',1,0,0, 46, TO_DATE('30/12/1991','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Cierra Runge','USA',1,0,0, 46, TO_DATE('07/03/1996','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Leah Neale','AUS',0,1,0, 46, TO_DATE('01/08/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Bronte Barratt','AUS',0,1,0, 46, TO_DATE('08/02/1989','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Tamsin Cook','AUS',0,1,0, 46, TO_DATE('25/12/1998', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Jessica Ashwood','AUS',0,1,0, 46, TO_DATE('28/04/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Katerine Savard','CAN',0,0,1, 46, TO_DATE('26/05/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Brittany Maclean','CAN',0,0,1, 46, TO_DATE('03/03/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Emily Overholt','CAN',0,0,1, 46, TO_DATE('04/10/1997', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Kennedy Goss','CAN',0,0,1, 46, TO_DATE('19/08/1996', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Ryan Murphy','USA',3,0,0, 45, TO_DATE('02/07/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Cody Miller','USA',1,0,1, 45, TO_DATE('09/01/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Chris Walker-Hebborn','GBR',0,1,0, 45, TO_DATE('01/07/1990','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Adam Peaty','GBR',1,1,0, 45, TO_DATE('28/12/1994','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Mitchell Larkin','AUS',0,1,1, 45, TO_DATE('09/07/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Jake Packard','AUS',0,0,1, 45, TO_DATE('20/06/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('David Morgan','AUS',0,0,1, 45, TO_DATE('01/01/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Kathleen Baker','USA',1,1,0, 46, TO_DATE('28/02/1997','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Lilly King','USA',2,0,0, 46, TO_DATE('10/02/1997', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Emily Seebohm','AUS',0,1,0, 46, TO_DATE('05/06/1992','DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Taylor Mckeown','AUS',0,1,0, 46, TO_DATE('17/03/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Mie Ostergaard Nielsen','DAN',0,0,1, 46, TO_DATE('25/09/1996', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Rikke Moeller Pedersen','DAN',0,0,1, 46, TO_DATE('09/01/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Jeanette Ottesen-Gray','DAN',0,0,1, 46, TO_DATE('30/12/1987', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Pernille Blume','DAN',1,0,1, 46, TO_DATE('14/05/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Niklas Landin Jacobsen','DAN',35, TO_DATE('19/12/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Mads Christiansen','DAN',35, TO_DATE('03/05/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Mads Mensah Larsen','DAN',35, TO_DATE('12/08/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Casper Ulrich Mortensen','DAN',35, TO_DATE('14/12/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Jesper Nøddesbo','DAN',35, TO_DATE('23/10/1980', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Jannick Green','DAN',35, TO_DATE('29/09/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Lasse Svan Hansen','DAN',35, TO_DATE('31/08/1983', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Rene Toft Hansen','DAN',35, TO_DATE('11/01/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Henrik Møllgaard','DAN',35, TO_DATE('02/01/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Kasper Søndergaard','DAN',35, TO_DATE('09/06/1981', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Henrik Toft Hansen','DAN',35, TO_DATE('18/12/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Mikkel Hansen','DAN',35, TO_DATE('22/10/1987', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Morten Olsen','DAN',35, TO_DATE('11/10/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport, age) values('Michael Damgaard','DAN',35, TO_DATE('18/03/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Daniel Narcisse','FRA',35, TO_DATE('16/12/1979', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Vincent Gérard','FRA',35, TO_DATE('16/12/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Nikola Karabatić','FRA',35, TO_DATE('11/4/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Kentin Mahé','FRA',35, TO_DATE('22/5/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Mathieu Grébille','FRA',35, TO_DATE('6/10/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Thierry Omeyer','FRA',35, TO_DATE('2/11/1976', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Timothey NGuessan','FRA',35, TO_DATE('18/9/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Luc Abalo','FRA',35, TO_DATE('6/9/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Cédric Sorhaindo','FRA',35, TO_DATE('7/6/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Michaël Guigou','FRA',35, TO_DATE('28/1/1982', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Luka Karabatić','FRA',35, TO_DATE('19/4/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Ludovic Fabregas','FRA',35, TO_DATE('1/7/1996', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Adrien Dipanda','FRA',35, TO_DATE('3/5/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Valentin Porte','FRA',35, TO_DATE('7/9/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Valentin Porte','FRA',35, TO_DATE('7/9/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Uwe Gensheimer','ALL',35, TO_DATE('26/10/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Finn Lemke','ALL',35, TO_DATE('30/4/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Patrick Wiencek','ALL',35, TO_DATE('22/3/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Tobias Reichmann','ALL',35, TO_DATE('27/5/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Fabian Wiede','ALL',35, TO_DATE('8/2/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Silvio Heinevetter','ALL',35, TO_DATE('21/10/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Hendrik Pekeler','ALL',35, TO_DATE('2/7/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Steffen Weinhold','ALL',35, TO_DATE('19/7/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Martin Strobel','ALL',35, TO_DATE('5/6/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Patrick Groetzki','ALL',35, TO_DATE('4/7/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Kai Häfner','ALL',35, TO_DATE('10/7/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Andreas Wolff','ALL',35, TO_DATE('3/3/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Julius Kühn','ALL',35, TO_DATE('1/4/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Christian Dissinger','ALL',35, TO_DATE('15/11/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Paul Drux','ALL',35, TO_DATE('7/2/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Anna Sedoykina','RUS',36, TO_DATE('1/8/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Polina Kuznetsova','RUS',36, TO_DATE('10/6/1987', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Daria Dmitrieva','RUS',36, TO_DATE('9/8/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Anna Sen','RUS',36, TO_DATE('3/2/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Olga Akopyan','RUS',36, TO_DATE('4/3/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Anna Vyakhireva','RUS',36, TO_DATE('13/3/1995', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Marina Sudakova','RUS',36, TO_DATE('17/2/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Vladlena Bobrovnikova','RUS',36, TO_DATE('24/10/1987', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Victoria Zhilinskayte','RUS',36, TO_DATE('6/3/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Yekaterina Marennikova','RUS',36, TO_DATE('29/4/1982', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Irina Bliznova','RUS',36, TO_DATE('6/10/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Ekaterina Ilina','RUS',36, TO_DATE('7/3/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Maya Petrova','RUS',36, TO_DATE('26/5/1982', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Tatyana Yerokhina','RUS',36, TO_DATE('7/9/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Victoriya Kalinina','RUS',36, TO_DATE('8/12/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Laura Glauser','FRA',36, TO_DATE('20/8/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Blandine Dancette','FRA',36, TO_DATE('14/2/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Camille Ayglon','FRA',36, TO_DATE('21/5/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Allison Pineau','FRA',36, TO_DATE('2/5/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Laurisa Landre','FRA',36, TO_DATE('27/10/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Grace Zaadi','FRA',36, TO_DATE('7/7/1993', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Amandine Leynaud','FRA',36, TO_DATE('2/5/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Manon Houette','FRA',36, TO_DATE('2/7/1992', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Siraba Dembélé','FRA',36, TO_DATE('28/6/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Chloé Bulleux','FRA',36, TO_DATE('18/11/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Béatrice Edwige','FRA',36, TO_DATE('3/10/1988', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Estelle Nze Minko','FRA',36, TO_DATE('11/8/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Gnonsiane Niombla','FRA',36, TO_DATE('9/7/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Alexandra Lacrabère','FRA',36, TO_DATE('27/4/1987', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Kari Aalvik Grimsbø','NOR',36, TO_DATE('4/1/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Mari Molid','NOR',36, TO_DATE('8/8/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Emilie Hegh Arntzen','NOR',36, TO_DATE('1/1/1994', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Veronica Kristiansen','NOR',36, TO_DATE('10/7/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Ida Alstad','NOR',36, TO_DATE('13/6/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Heidi Løke','NOR',36, TO_DATE('12/12/1982', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Nora Mørk','NOR',36, TO_DATE('5/4/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Stine Bredal Oftedal','NOR',36, TO_DATE('25/9/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Marit Malm Frafjord','NOR',36, TO_DATE('25/11/1985', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Katrine Lunde','NOR',36, TO_DATE('30/3/1980', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Linn-Kristin Riegelhuth Koren','NOR',36, TO_DATE('1/8/1984', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Amanda Kurtović','NOR',36, TO_DATE('25/7/1991', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Camilla Herrem','NOR',36, TO_DATE('8/10/1986', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Sanna Solberg','NOR',36, TO_DATE('16/6/1990', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Eleonora Giorgi','ITA',2, TO_DATE('14/09/1989', 'DD/MM/YYYY'));
insert into Athlete(nom, code_pays, id_sport,age) values('Ayomide Folorunso','ITA',2, TO_DATE('17/10/1996', 'DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Niccolo Campriani','ITA',2,0,0, 63, TO_DATE('06/11/1987', 'DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Daniele Garozzo','ITA',1,1,0, 23, TO_DATE('04/08/1992','DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Gregorio Paltrinieri','ITA',1,0,0,45, TO_DATE('05/09/1994','DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Fabio Basile','ITA',1,0,0, 39, TO_DATE('07/10/1994','DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Diana Bacosi','ITA',1,0,0, 63, TO_DATE('13/07/1983','DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Gabriele Rossetti','ITA',1,0,0, 63, TO_DATE('07/03/1995','DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Elia Viviani','ITA',1,0,0, 17, TO_DATE('07/02/1989', 'DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Tania Cagnotto','ITA',0,1,1, 54, TO_DATE('15/05/1985', 'DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Odette Giuffrida','ITA',0,1,0, 40, TO_DATE('12/10/1994', 'DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Paolo Pizzo','ITA',0,1,0, 23, TO_DATE('04/04/1983', 'DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Rossella Fiamingo','ITA',0,1,0, 24, TO_DATE('14/07/1991', 'DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Elisa Di Francisca','ITA',0,1,0, 24, TO_DATE('13/12/1982', 'DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Marco Fichera','ITA',0,1,0, 23, TO_DATE('15/04/1993', 'DD/MM/YYYY'));
  insert into Athlete(nom, code_pays,  nb_medailles_or, nb_medailles_argent, nb_medailles_bronze, id_sport, age) values('Andrea Santarelli','ITA',0,1,0, 23, TO_DATE('03/06/1993', 'DD/MM/YYYY'));

--Pour calculer le total de nb_medailles
update athlete set nb_medailles_total=(select (a.nb_medailles_or+a.nb_medailles_argent+a.nb_medailles_bronze) from athlete a where a.id_athlete = athlete.id_athlete);
--Pour la colonne rang, le rangement des athletes
create view rank2 as select a1.*, row_number() over(order by a1.nb_medailles_or desc, a1.nb_medailles_argent desc, a1.nb_medailles_bronze desc, a1.nom asc) from athlete a1, athlete a2 where a1.id_athlete=a2.id_athlete;
update athlete set rang=(select row_number from rank2 where rank2.id_athlete=athlete.id_athlete);

-- EpreuveIndividuelle
insert into epreuveindividuelle (nom_epreuve, id_sport) values('100m (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('100m (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('400m (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('400m (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('marathon (H)', 1);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('marathon (F)', 2);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('100m Papillon (H)', 45);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('100m Papillon (F)', 46);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m Papillon (H)', 45);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m Papillon (F)', 46);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m 4 nages (H)', 45);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m 4 nages (F)', 46);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('4x100m nage libre (H)', 45);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('4x100m nage libre (F)', 46);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m nage libre (H)', 45);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('200m nage libre (F)', 46);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('4x200m nage libre (H)', 45);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('4x200m nage libre (F)', 46);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('4x100m 4 nage (H)', 45);
insert into epreuveindividuelle (nom_epreuve, id_sport) values('4x100m 4 nage (F)', 46);

-- Athlete_EpreuveIndividuelle
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(3,1,'or', '00:00:09.81'); --100m hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(1,1,'argent','00:00:09.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(2,1,'bronze','00:00:09.91');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(3,3,'or','00:00:19.78'); --200m hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(2,3,'argent','00:00:20.02');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(4,3,'bronze','00:00:20.12');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(5,5,'or','00:00:43.03'); --400m hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(6,5,'argent','00:00:43.76');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(7,5,'bronze','00:00:43.85');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(15,7,'or','02:08:44'); --marathon hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(16,7,'argent','02:09:54');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(17,7,'bronze','2:10:05');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(8,2,'or','00:00:10.71'); --100m femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(9,2,'argent','00:00:10.83');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(10,2,'bronze','00:00:10.86');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(8,4,'or','00:00:21.78'); --200m femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(11,4,'argent','00:00:21.88');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(9,4,'bronze','00:00:22.15');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(12,6,'or','00:00:49.44'); --400m femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(13,6,'argent','00:00:49.51');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(14,6,'bronze','00:00:49.85');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(18,8,'or','02:24:04'); --marathon femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(19,8,'argent','02:24:13');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(20,8,'bronze','02:24:30');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(21,9,'or','00:00:50.39'); --100m papillon hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(22,9,'argent','00:00:51.14');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(23,9,'argent','00:00:51.14');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(24,9,'argent','00:00:51.14');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(22,11,'or','00:01:53.36'); --100m papillon hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(25,11,'argent','00:01:53.40');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(26,11,'bronze','00:01:53.62');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(22,13,'or','00:01:54.66'); --200m 4 nages hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(27,13,'argent','00:01:56.61');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(28,13,'bronze','00:01:57.05');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(29,10,'or','00:00:55.48'); --100m papillon femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(30,10,'argent','00:00:56.46');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(31,10,'argent','00:00:56.63');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(32,12,'or','00:02:04.85'); --100m papillon femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(33,12,'argent','00:02:04.88');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(34,12,'bronze','00:02:05.20');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(35,14,'or','00:02:05.58'); --200m 4 nages femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(36,14,'argent','00:02:06.88');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(37,14,'bronze','00:02:08.79');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(38,15,'or','00:03:09.92'); --4x100m nage libre hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(22,15,'or','00:03:09.92');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(39,15,'or','00:03:09.92');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(40,15,'or','00:03:09.92');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(41,15,'or','00:03:09.92');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(42,15,'or','00:03:09.92');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(43,15,'or','00:03:09.92');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(44,15,'argent','00:03:10.53');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(45,15,'argent','00:03:10.53');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(46,15,'argent','00:03:10.53');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(47,15,'argent','00:03:10.53');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(48,15,'argent','00:03:10.53');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(49,15,'argent','00:03:10.53');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(50,15,'bronze','00:03:11.37');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(51,15,'bronze','00:03:11.37');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(52,15,'bronze','00:03:11.37');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(53,15,'bronze','00:03:11.37');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(54,15,'bronze','00:03:11.37');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(55,16,'or','00:03:30.65'); --4x100m nage libre femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(56,16,'or','00:03:30.65');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(57,16,'or','00:03:30.65');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(58,16,'or','00:03:30.65');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(59,16,'or','00:03:30.65');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(60,16,'argent','00:03:31.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(61,16,'argent','00:03:31.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(31,16,'argent','00:03:31.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(62,16,'argent','00:03:31.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(63,16,'argent','00:03:31.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(64,16,'argent','00:03:31.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(65,16,'argent','00:03:31.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(66,16,'bronze','00:03:32.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(67,16,'bronze','00:03:32.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(68,16,'bronze','00:03:32.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(30,16,'bronze','00:03:32.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(69,16,'bronze','00:03:32.89');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(70,19,'or','00:07:00.66'); --4x200m nage libre hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(71,19,'or','00:07:00.66');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(72,19,'or','00:07:00.66');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(22,19,'or','00:07:00.66');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(73,19,'or','00:07:00.66');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(74,19,'or','00:07:00.66');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(75,19,'or','00:07:00.66');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(76,19,'argent','00:07:03.13');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(77,19,'argent','00:07:03.13');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(78,19,'argent','00:07:03.13');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(79,19,'argent','00:07:03.13');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(80,19,'argent','00:07:03.13');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(27,19,'bronze','00:07:03.50');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(81,19,'bronze','00:07:03.50');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(82,19,'bronze','00:07:03.50');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(83,19,'bronze','00:07:03.50');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(65,20,'or','00:07:43.03'); --4x200m nage libre femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(84,20,'or','00:07:43.03');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(37,20,'or','00:07:43.03');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(62,20,'or','00:07:43.03');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(85,20,'or','00:07:43.03');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(86,20,'or','00:07:43.03');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(87,20,'or','00:07:43.03');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(88,20,'argent','00:07:44.87');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(55,20,'argent','00:07:44.87');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(89,20,'argent','00:07:44.87');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(90,20,'argent','00:07:44.87');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(91,20,'argent','00:07:44.87');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(92,20,'bronze','00:07:45.39');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(68,20,'bronze','00:07:45.39');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(93,20,'bronze','00:07:45.39');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(30,20,'bronze','00:07:45.39');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(94,20,'bronze','00:07:45.39');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(95,20,'bronze','00:07:45.39');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(96,21,'or','00:03:27.95'); --4x100m 4 nage hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(97,21,'or','00:03:27.95');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(22,21,'or','00:03:27.95');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(40,21,'or','00:03:27.95');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(98,21,'argent','00:03:29.24');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(99,21,'argent','00:03:29.24');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(79,21,'argent','00:03:29.24');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(77,21,'argent','00:03:29.24');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(100,21,'bronze','00:03:29.93');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(101,21,'bronze','00:03:29.93');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(102,21,'bronze','00:03:29.93');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(51,21,'bronze','00:03:29.93');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(103,22,'or','00:03:53.13'); --4x100m 4 nage femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(104,22,'or','00:03:53.13');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(31,22,'or','00:03:53.13');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(60,22,'or','00:03:53.13');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(105,22,'argent','00:03:55.00');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(106,22,'argent','00:03:55.00');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(55,22,'argent','00:03:55.00');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(58,22,'argent','00:03:55.00');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(107,22,'bronze','00:03:55.01');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(108,22,'bronze','00:03:55.01');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(109,22,'bronze','00:03:55.01');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(110,22,'bronze','00:03:55.01');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(111,17,'or','00:01:44.65'); --200m nage libre hommes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(24,17,'argent','00:01:45.20');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(70,17,'bronze','00:01:45.23');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(62,18,'or','00:01:53.73'); --200m nage libre femmes
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(29,18,'argent','00:01:54.08');
insert into athlete_epreuveindividuelle (id_athlete, id_epreuve, medaille, performance) values(55,18,'bronze','00:01:54.92');

--EpreuveCollective
insert into epreuvecollective (id_sport) values (35);
insert into epreuvecollective (id_sport) values (36);
insert into epreuvecollective (id_sport) values (25);
insert into epreuvecollective (id_sport) values (26);
insert into epreuvecollective (id_sport) values (9);
insert into epreuvecollective (id_sport) values (10);
insert into epreuvecollective (id_sport) values (11);
insert into epreuvecollective (id_sport) values (12);
insert into epreuvecollective (id_sport) values (75);
insert into epreuvecollective (id_sport) values (76);
insert into epreuvecollective (id_sport) values (77);
insert into epreuvecollective (id_sport) values (78);
insert into epreuvecollective (id_sport) values (55);
insert into epreuvecollective (id_sport) values (56);

--Equipes
insert into equipe(code_pays, id_sport) values('DAN', 35); --pour handball hommes
insert into equipe(code_pays, id_sport) values('FRA', 35);
insert into equipe(code_pays, id_sport) values('ALL', 35);
insert into equipe(code_pays, id_sport) values('RUS', 36); --pour handball femmes
insert into equipe(code_pays, id_sport) values('FRA', 36);
insert into equipe(code_pays, id_sport) values('NOR', 36);
insert into equipe(code_pays, id_sport) values('POL', 35);
insert into equipe(code_pays, id_sport) values('HOL', 36);
insert into equipe(code_pays, id_sport) values('BRE', 25); --pour football hommes
insert into equipe(code_pays, id_sport) values('ALL', 25);
insert into equipe(code_pays, id_sport) values('NIG', 25);
insert into equipe(code_pays, id_sport) values('HON', 25);
insert into equipe(code_pays, id_sport) values('ALL', 26); --pour football femmes
insert into equipe(code_pays, id_sport) values('SUE', 26);
insert into equipe(code_pays, id_sport) values('CAN', 26);
insert into equipe(code_pays, id_sport) values('BRE', 26);



--Equipe_EpreuveCollective
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(1, 1, 'or'); --handball hommes
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(1, 2, 'argent');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(1, 3, 'bronze');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(2, 4, 'or'); --handball femmes
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(2, 5, 'argent');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(2, 6, 'bronze');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(3, 9, 'or'); --football hommes
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(3, 10, 'argent');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(3, 11, 'bronze');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(4, 13, 'or'); --football femmes
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(4, 14, 'argent');
insert into equipe_epreuvecollective(id_epreuve, id_equipe, medaille) values(4, 15, 'bronze');

--Resultats_Equipe
insert into resultats_equipe(id_epreuve, id_gagnant, id_perdant, score) values(1,1,2,'28-26');
insert into resultats_equipe(id_epreuve, id_gagnant, id_perdant, score) values(1,3,7,'31-25');
insert into resultats_equipe(id_epreuve, id_gagnant, id_perdant, score) values(2,4,2,'22-19');
insert into resultats_equipe(id_epreuve, id_gagnant, id_perdant, score) values(2,6,8,'26-36');
insert into resultats_equipe(id_epreuve, id_gagnant, id_perdant, score) values(3,9,10,'6-5');
insert into resultats_equipe(id_epreuve, id_gagnant, id_perdant, score) values(3,11,12,'3-2');
insert into resultats_equipe(id_epreuve, id_gagnant, id_perdant, score) values(4,13,14,'2-1');
insert into resultats_equipe(id_epreuve, id_gagnant, id_perdant, score) values(4,15,16,'2-1');
